### PR TITLE
CI: collect kind logs on integration testing

### PR DESCRIPTION
**Pull request by eloycoto**

### CODE REVIEW

**Review by RichardW98 — APPROVED** [review]

**Comment by eloycoto** [comment]
This action is not executed because It is using pull request target, please if you are happy, please merge it.

**Review by gciavarrini — APPROVED** [review]
lgtm

**Review by gciavarrini — APPROVED** [review]
/lgtm

**Review by pkliczewski — COMMENTED** [review]
/lgtm

**Pull request merged**
