### PR TITLE
java format plugin

### PR DESCRIPTION
**Pull request by RichardW98**
add plugin "**spring-javaformat-maven-plugin**". in parent pom for **Code Format**

to fix code format, go to the folder of parent pom and run "spring-javaformat:apply"
Screenshot 2023-02-09 at 11 42 08 AM

### CODE REVIEW

**Comment by eloycoto** [comment]
May I propose to have a step before testing that it's `maven validate` so if the build fails, we know that it's a format issue and no test issue without looking at the specific details

**Comment by eloycoto** [comment]
And I would suggest to rebase, I added yesterday this commit:
https://github.com/redhat-developer/parodos/blob/main/.github/workflows/test.yml

**Comment by RichardW98** [comment]
test.yml are rebased. please review again

**Comment by eloycoto** [comment]
LGTM, all are style changes, so it's ok for me. I'll squash the commits in there.

**Comment by RichardW98** [comment]
all commits squashed

**Review by anludke — APPROVED** [review]

**Pull request merged**
