### PR TITLE
FLPATH-204: cleanup definitions in db before loading new beans

### PR DESCRIPTION
**Pull request by RichardW98**
[FLPATH-204](https://issues.redhat.com/browse/FLPATH-204)

update database with new workflow configuration after app restarts

*note:   executions and project table are not cleaned

### CODE REVIEW

**Review by pkliczewski — COMMENTED** [review]
looks good, please add a test

**Comment by RichardW98** [comment]
tests added

**Comment by masayag** [comment]
lgtm

**Comment by RichardW98** [comment]
> What will happen if there are tasks execution or workflow execution in the DB ? Wouldn't it cause reference key constrain violation? Perhaps there is a need to check there are not executions of any kind before deleting?

yes, the executions will be deleted as well if its definition is removed. I will change the logic from removing definitions to updating/adding

**Pull request merged**
