### PR TITLE
Fix example parameters names

### PR DESCRIPTION
**Pull request by nirarg**
following to this commit: https://github.com/redhat-developer/parodos/commit/de70236616c349a1b7abaac04139bb52dff92b2f

### CODE REVIEW

**Review by pkliczewski — COMMENTED** [review]
/lgtm

**Comment by pkliczewski** [comment]
I wonder why CI was green before this changes. Are we not checking correctly the result of the tests?

**Comment by eloycoto** [comment]
Not the simple workflow and the change in yaml workflows are not in there until it got merged.

**Review by RichardW98 — APPROVED** [review]

**Review by pkliczewski — COMMENTED** [review]
/lgtm

**Pull request merged**
