### PR TITLE
FLPATH-36 publish mvn modules

### PR DESCRIPTION
**Pull request by pkliczewski**
In PR introduced changes to our pom files to enable publsihing our modules to maven central repo. There are two new make stargets deploy and release. In order to be able to publish we need to create settings.xml file in ~/.m2 directory with maven central user info for [Jira](https://issues.sonatype.org/). 

```xml
<settings>
  <servers>
    <server>
      <id>ossrh</id>
      <username>your-jira-id</username>
      <password>your-jira-pwd</password>
    </server>
  </servers>
</settings>
```

Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

### CODE REVIEW

**Review by gciavarrini — COMMENTED** [review]
Overall LGTM.

Question: Do you think that a dedicated section in the README can be beneficial for new contributors?

**Review by gciavarrini — APPROVED** [review]
lgtm

**Review by RichardW98 — APPROVED** [review]

**Comment by pkliczewski** [comment]
@lshannon @anludke please take a look

**Comment by pkliczewski** [comment]
Rebase needed after recent changes.

@RichardW98 @lshannon first release staged. Once this PR is merged I will push version update and will tag the release commit.

**Comment by anludke** [comment]
@pkliczewski we should also update the source packages to align with the new parent > groupId dev.parodos

**Review by anludke — CHANGES_REQUESTED** [review]
We'll update source packages to align with the new parent > projectId

**Comment by pkliczewski** [comment]
@anludke we do not need to align our packages with groupId. Please take a look at artifacts from `org.ceylon-lang`

**Review by anludke — APPROVED** [review]

**Comment by pkliczewski** [comment]
I updated pushing javadoc and sources in the release profile. As well added developers section.

**Pull request merged**
